<li><?= $this->Html->link('Articles', array('admin' => true, 'plugin' => false, 'controller' => 'articles', 'action' => 'admin_index')) ?></li>
<li><?= $this->Html->link('Users', array('admin' => true, 'plugin' => false, 'controller' => 'users', 'action' => 'admin_index')) ?></li>
<li><?= $this->Html->link('Categories', array('admin' => true, 'plugin' => false, 'controller' => 'categories', 'action' => 'admin_index')) ?></li>
<li><?= $this->Html->link('Fields', array('admin' => true, 'plugin' => false, 'controller' => 'fields', 'action' => 'admin_index')) ?></li>
<li><?= $this->Html->link('Pages', array('admin' => true, 'plugin' => false, 'controller' => 'pages', 'action' => 'admin_index')) ?></li>
<li><?= $this->Html->link('Files', array('admin' => true, 'plugin' => false, 'controller' => 'files', 'action' => 'admin_index')) ?></li>
<li><?= $this->Html->link('Roles', array('admin' => true, 'plugin' => false, 'controller' => 'roles', 'action' => 'admin_index')) ?></li>
<li><?= $this->Html->link('Settings', array('admin' => true, 'plugin' => false, 'controller' => 'settings', 'action' => 'admin_index')) ?></li>
<li><?= $this->Html->link('Appearance', array('admin' => true, 'plugin' => false, 'controller' => 'templates', 'action' => 'admin_index')) ?></li>
<li><?= $this->Html->link('Modules', array('admin' => true, 'plugin' => false, 'controller' => 'modules', 'action' => 'admin_index')) ?></li>