<?= "<?xml version='1.0' encoding='UTF-8'?>" ?>
<?= "<?xml-stylesheet type='text/xsl' href='" . Router::url('/', true) . "SitemapGenerator/gss.xsl'?>" ?>
<urlset xmlns='http://www.sitemaps.org/schemas/sitemap/0.9' xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance' xsi:schemaLocation='http://www.sitemaps.org/schemas/sitemap/0.9 http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd'>
	<!--#Generated by AdaptCMS Sitemap Generator by Charlie Page, http://www.adaptcms.com -->
	<url>
		<loc><?= Router::url('/', true) ?></loc>
		<lastmod><?= date('Y-m-d') ?></lastmod>
		<changefreq>daily</changefreq>
		<priority>1.00</priority>
	</url>
	<?php foreach($data['articles'] as $article): ?>
		<url>
			<loc>
				<?= $this->Html->url(array(
                    'admin' => false,
                    'plugin' => false,
					'controller' => 'articles',
					'action' => 'view',
                    'slug' => $article['Article']['slug'],
                    'id' => $article['Article']['id']
				), true) ?>

			</loc>
			<lastmod><?= date("Y-m-d", strtotime($article['Article']['modified'])) ?></lastmod>
			<changefreq>daily</changefreq>
			<priority>0.50</priority>
		</url>
	<?php endforeach ?>
	<?php foreach($data['categories'] as $category): ?>
		<url>
			<loc>
				<?= $this->Html->url(array(
                    'admin' => false,
                    'plugin' => false,
					'controller' => 'categories',
					'action' => 'view',
					$category['Category']['slug']
				), true) ?>

			</loc>
			<lastmod><?= date("Y-m-d", strtotime($category['Category']['modified'])) ?></lastmod>
			<changefreq>daily</changefreq>
			<priority>0.50</priority>
		</url>
	<?php endforeach ?>
	<?php foreach($data['libraries'] as $media): ?>
		<url>
			<loc>
				<?= $this->Html->url(array(
                    'admin' => false,
                    'plugin' => false,
					'controller' => 'media',
					'action' => 'view',
					$media['Media']['slug']
				), true) ?>

			</loc>
			<lastmod><?= date("Y-m-d", strtotime($media['Media']['modified'])) ?></lastmod>
			<changefreq>daily</changefreq>
			<priority>0.50</priority>
		</url>
		<?php $media_time = strtotime($media['Media']['modified']) ?>
	<?php endforeach ?>
	<url>
		<loc>
			<?= $this->Html->url(array(
                'admin' => false,
                'plugin' => false,
				'controller' => 'media',
				'action' => 'index'
			), true) ?>

		</loc>
		<lastmod><?= date("Y-m-d", !empty($media_time) ? $media_time : time()) ?></lastmod>
		<changefreq>daily</changefreq>
		<priority>0.50</priority>
	</url>

	<?php foreach($data['pages'] as $page): ?>
		<url>
			<loc>
				<?= $this->Html->url(array(
                    'admin' => false,
                    'plugin' => false,
					'controller' => 'pages',
					'action' => 'display',
					$page['Page']['slug']
				), true) ?>

			</loc>
			<lastmod><?= date("Y-m-d", strtotime($page['Page']['modified'])) ?></lastmod>
			<changefreq>daily</changefreq>
			<priority>0.50</priority>
		</url>
	<?php endforeach ?>
	<?php foreach($data['users'] as $user): ?>
		<url>
			<loc>
				<?= $this->Html->url(array(
                    'admin' => false,
                    'plugin' => false,
					'controller' => 'users',
					'action' => 'profile',
					$user['User']['username']
				), true) ?>

			</loc>
			<lastmod><?= date("Y-m-d", strtotime($user['User']['modified'])) ?></lastmod>
			<changefreq>daily</changefreq>
			<priority>0.50</priority>
		</url>
	<?php endforeach ?>
</urlset>