INSERT INTO `{prefix}articles` (`id`, `title`, `slug`, `tags`, `related_articles`, `user_id`, `category_id`, `status`, `publish_time`, `created`, `modified`, `deleted_time`) VALUES
(1, 'Welcome to AdaptCMS 3.0.2!', 'welcome-to-adaptcms-3-0-2', NULL, '', 1, 1, 1, '{date}', '{date}', '{date}', '0000-00-00 00:00:00');
-- --------------------------------------------------------
INSERT INTO `{prefix}article_values` (`id`, `article_id`, `field_id`, `file_id`, `data`) VALUES
(1, 1, 1, 0, '<p>We hope you enjoy your newly installed copy of AdaptCMS. Be sure to check the <a href="http://www.adaptcms.com" target="_blank">official website</a> for documentation on the CMS and you can get support <a href="http://www.adaptcms.com/support" target="_blank">here</a>. Enjoy!</p>\r\n<p>Thank you,<br />AdaptCMS Team</p>');
-- --------------------------------------------------------
INSERT INTO `{prefix}blocks` (`id`, `title`, `type`, `module_id`, `user_id`, `limit`, `settings`, `data`, `created`, `modified`, `deleted_time`) VALUES
(1, 'show-poll', 'dynamic', 8, 1,  1, '{"order_by":"created","order_dir:"desc"}', null, '{date}', '{date}', '0000-00-00 00:00:00'),
(2, 'latest-links', 'dynamic', 17, 1, 3, '{"order_by":"created","order_dir":"asc"}', null, '{date}', '{date}', '0000-00-00 00:00:00'),
(3, 'admin-main-articles-newest', 'dynamic', 1, 1, 5, '{"category_id":"","order_by":"created","order_dir":"desc"}', null, '{date}', '{date}', '0000-00-00 00:00:00'),
(4, 'admin-main-users-newest', 'dynamic', 9, 1, 5, '{"order_by":"created","order_dir":"desc"}', null, '{date}', '{date}', '0000-00-00 00:00:00');
-- --------------------------------------------------------
INSERT INTO `{prefix}categories` (`id`, `title`, `slug`, `settings`, `user_id`, `created`, `modified`, `deleted_time`) VALUES
(1, 'News', 'news', null, 1, '{date}', '{date}', '0000-00-00 00:00:00');
-- --------------------------------------------------------
INSERT INTO `{prefix}fields` (`id`, `title`, `label`, `field_order`, `category_id`, `module_id`, `field_type_id`, `field_type_slug`, `description`, `field_options`, `field_limit_min`, `field_limit_max`, `required`, `user_id`, `created`, `modified`, `deleted_time`) VALUES
(1, 'summary', 'summary', 0, 1, 0, 11, 'textarea', 'You ought to enter a short summary of the news article.', '', 0, 0, 1, 1, '{date}', '{date}', '0000-00-00 00:00:00');
-- --------------------------------------------------------
INSERT INTO `{prefix}field_types` (`id`, `title`, `label`, `slug`, `limit`, `user_id`, `ord`, `active`, `created`, `modified`, `deleted_time`) VALUES
(null, 'text', 'Text Input', 'text', 1, 1, 0, 1, '{date}', '{date}', '0000-00-00 00:00:00'),
(null, 'Check', 'Checkbox', 'check', 0, 1, 0, 1, '{date}', '{date}', '0000-00-00 00:00:00'),
(null, 'Date', '', 'date', 0, 1, 0, 1, '{date}', '{date}', '0000-00-00 00:00:00'),
(null, 'Dropdown', 'Dropdown Selector', 'dropdown', 0, 1, 0, 1, '{date}', '{date}', '0000-00-00 00:00:00'),
(null, 'Email', '', 'email', 1, 1, 0, 1, '{date}', '{date}', '0000-00-00 00:00:00'),
(null, 'File', '', 'file', 0, 1, 0, 1, '{date}', '{date}', '0000-00-00 00:00:00'),
(null, 'Img', 'Image', 'img', 0, 1, 0, 1, '{date}', '{date}', '0000-00-00 00:00:00'),
(null, 'Multi Dropdown', 'Dropdown Selector Multiple', 'multi-dropdown', 0, 1, 0, 1, '{date}', '{date}', '0000-00-00 00:00:00'),
(null, 'Num', 'Number', 'num', 1, 1, 0, 1, '{date}', '{date}', '0000-00-00 00:00:00'),
(null, 'Radio', '', 'radio', 0, 1, 0, 1, '{date}', '{date}', '0000-00-00 00:00:00'),
(null, 'Textarea', 'Text Box', 'textarea', 1, 1, 0, 1, '{date}', '{date}', '0000-00-00 00:00:00'),
(null, 'Url', 'Website  URL', 'url', 1, 1, 0, 1, '{date}', '{date}', '0000-00-00 00:00:00');
-- --------------------------------------------------------
INSERT INTO `{prefix}modules` (`id`, `title`, `model_title`, `block_active`, `is_plugin`, `is_searchable`, `is_fields`) VALUES
(1, 'Articles', 'Article', 1, 0, 1, 0),
(2, 'Blocks', 'Block', 0, 0, 0, 0),
(3, 'Categories', 'Category', 1, 0, 0, 0),
(4, 'Files', 'File', 1, 0, 0, 0),
(5, 'Fields', 'Field', 0, 0, 0, 0),
(6, 'Templates', 'Template', 0, 0, 0, 0),
(7, 'Themes', 'Theme', 0, 0, 0, 0),
(8, 'Polls', 'Poll', 1, 1, 0, 0),
(9, 'Users', 'User', 1, 0, 0, 1),
(10, 'Pages', 'Page', 0, 0, 0, 0),
(11, 'Roles', 'Role', 0, 0, 0, 0),
(12, 'Settings', 'Setting', 0, 0, 0, 0),
(13, 'Setting Values', 'SettingValue', 0, 0, 0, 0),
(14, 'Permissions', 'Permission', 0, 0, 0, 0),
(15, 'Support Tickets', 'Ticket', 0, 1, 0, 0),
(16, 'Media', 'Media', 0, 0, 0, 0),
(17, 'Links', 'Link', 1, 1, 1, 0),
(18, 'Messages', 'message', 0, 0, 0, 0),
(19, 'Cron', 'cron', 0, 0, 0, 0),
(20, 'Comments', 'comment', 1, 0, 0, 1),
(21, 'AdaptBB', 'ForumPost', 1, 1, 0, 1),
(22, 'Google Maps', 'GoogleMaps', 1, 1, 0, 0);
-- --------------------------------------------------------
INSERT INTO `{prefix}pages` (`id`, `title`, `slug`, `user_id`, `created`, `modified`, `deleted_time`) VALUES
(1, 'Contact Us', 'contact-us', 1, '{date}', '{date}', '0000-00-00 00:00:00'),
(2, 'Home', 'home', 1, '{date}', '{date}', '0000-00-00 00:00:00');
-- --------------------------------------------------------
INSERT INTO `{prefix}permissions` (`id`, `label`, `module_id`, `role_id`, `action_id`, `plugin`, `controller`, `action`, `status`, `related`, `own`, `any`) VALUES
(null, null, 9, 1, 0, '', 'users', 'admin_index', 1, '[{"action":["admin_add"]},{"action":["admin_edit"]},{"action":["admin_delete"]},{"action":["admin_restore"]},{"action":["profile"]},{"action":["admin_ajax_change_user"]}]', 1, 1),
(null, null, 11, 1, 0, '', 'roles', 'admin_index', 1, '[{"action":["admin_add"]},{"action":["admin_edit"]},{"action":["admin_delete"]},{"action":["admin_restore"]}]', 2, 2),
(null, null, 11, 1, 0, '', 'roles', 'admin_add', 1, NULL, 0, 0),
(null, null, 11, 1, 0, '', 'roles', 'admin_edit', 1, NULL, 2, 2),
(null, null, 11, 1, 0, '', 'roles', 'admin_delete', 1, NULL, 2, 2),
(null, null, 0, 1, 0, '', 'permissions', 'admin_add', 1, NULL, 0, 0),
(null, null, 6, 1, 0, '', 'templates', 'admin_restore', 1, '', 1, 1),
(null, null, 1, 1, 0, '', 'articles', 'admin_index', 1, '[{"action":["admin_add"]},{"action":["admin_edit"]},{"action":["admin_delete"]},{"action":["admin_restore"]},{"action":["view"]},{"action":["profile"],"controller":["users"]}]', 1, 1),
(null, null, 1, 1, 0, '', 'articles', 'admin_add', 1, NULL, 0, 0),
(null, null, 1, 1, 0, '', 'articles', 'admin_edit', 1, NULL, 1, 1),
(null, null, 3, 1, 0, '', 'categories', 'admin_index', 1, '[{"action":["admin_add"]},{"action":["admin_edit"]},{"action":["admin_delete"]},{"action":["admin_restore"]},{"action":["view"]},{"action":["profile"],"controller":["users"]}]', 1, 1),
(null, null, 5, 1, 0, '', 'fields', 'admin_index', 1, '[{"action":["admin_add"]},{"action":["admin_edit"]},{"action":["admin_delete"]},{"action":["admin_restore"]},{"action":["profile"],"controller":["users"]}]', 1, 1),
(null, null, 10, 1, 0, '', 'pages', 'admin_index', 1, '[{"action":["admin_add"]},{"action":["admin_edit"]},{"action":["admin_delete"]},{"action":["admin_restore"]},{"action":["display"]},{"action":["profile"],"controller":["users"]}]', 1, 1),
(null, null, 12, 1, 0, '', 'settings', 'admin_index', 1, '[{"action":["admin_add"]},{"action":["admin_edit"]},{"action":["admin_delete"]},{"action":["admin_restore"]}]', 1, 1),
(null, null, 8, 1, 0, 'polls', 'polls', 'admin_restore', 1, '', 1, 1),
(null, null, 10, 1, 0, '', 'pages', 'admin_edit', 1, NULL, 1, 1),
(null, null, 10, 1, 0, '', 'pages', 'admin_add', 1, NULL, 0, 0),
(null, null, 10, 1, 0, '', 'pages', 'admin_delete', 1, NULL, 1, 1),
(null, null, 12, 1, 0, '', 'settings', 'admin_add', 1, NULL, 0, 0),
(null, null, 12, 1, 0, '', 'settings', 'admin_edit', 1, NULL, 1, 1),
(null, null, 12, 1, 0, '', 'settings', 'admin_delete', 1, NULL, 1, 1),
(null, null, 13, 1, 0, '', 'setting_values', 'admin_add', 1, NULL, 0, 0),
(null, null, 13, 1, 0, '', 'setting_values', 'admin_edit', 1, NULL, 1, 1),
(null, null, 5, 1, 0, '', 'fields', 'admin_add', 1, NULL, 0, 0),
(null, null, 5, 1, 0, '', 'fields', 'admin_edit', 1, NULL, 1, 1),
(null, null, 1, 1, 0, '', 'articles', 'view', 1, '[{"action":["ajax_post"], "controller":["comments"]},{"action":["admin_edit"], "controller":["comments"]},{"action":["admin_delete"], "controller":["comments"]}]', 1, 1),
(null, null, 9, 1, 0, '', 'users', 'admin_add', 1, NULL, 0, 0),
(null, null, 9, 1, 0, '', 'users', 'admin_edit', 1, NULL, 1, 1),
(null, null, 8, 1, 0, 'polls', 'polls', 'admin_index', 1, '[{"action":["admin_add"]},{"action":["admin_edit"]},{"action":["admin_delete"]},{"action":["admin_restore"]},{"action":["profile"],"controller":["users"]}]', 1, 1),
(null, null, 8, 1, 0, 'polls', 'polls', 'admin_add', 1, NULL, 0, 0),
(null, null, 8, 1, 0, 'polls', 'polls', 'admin_delete', 1, NULL, 1, 1),
(null, null, 8, 1, 0, 'polls', 'polls', 'admin_edit', 1, NULL, 1, 1),
(null, null, 3, 1, 0, '', 'categories', 'admin_add', 1, NULL, 0, 0),
(null, null, 3, 1, 0, '', 'categories', 'admin_edit', 1, NULL, 1, 1),
(null, null, 3, 1, 0, '', 'categories', 'view', 1, NULL, 1, 1),
(null, null, 10, 1, 0, '', 'pages', 'display', 1, '[{"action":["view"],"controller":["articles"]}]', 2, 2),
(null, null, 4, 1, 0, '', 'files', 'admin_index', 1, '[{"action":["admin_add"]},{"action":["admin_add_folder"]},{"action":["admin_edit"]},{"action":["admin_delete"]},{"action":["admin_restore"]},{"action":["view"]}]', 1, 1),
(null, null, 4, 1, 0, '', 'files', 'admin_add', 1, NULL, 0, 0),
(null, null, 4, 1, 0, '', 'files', 'admin_edit', 1, NULL, 1, 1),
(null, null, 4, 1, 0, '', 'files', 'admin_delete', 1, NULL, 1, 1),
(null, null, 6, 1, 0, '', 'templates', 'admin_index', 1, '[{"action":["admin_add"]},{"action":["admin_edit"]},{"action":["admin_delete"]},{"action":["admin_restore"]}]', 1, 1),
(null, null, 6, 1, 0, '', 'templates', 'admin_add', 1, NULL, 0, 0),
(null, null, 6, 1, 0, '', 'templates', 'admin_edit', 1, NULL, 1, 1),
(null, null, 6, 1, 0, '', 'templates', 'admin_delete', 1, NULL, 1, 1),
(null, null, 7, 1, 0, '', 'themes', 'admin_add', 1, NULL, 0, 0),
(null, null, 7, 1, 0, '', 'themes', 'admin_edit', 1, '[{"action":["admin_asset_add"]},{"action":["admin_asset_edit"]},{"action":["admin_asset_delete"]}]', 1, 1),
(null, null, 7, 1, 0, '', 'themes', 'admin_delete', 1, NULL, 1, 1),
(null, null, 7, 1, 0, '', 'themes', 'admin_restore', 1, '', 1, 1),
(null, null, 2, 1, 0, '', 'blocks', 'admin_add', 1, NULL, 0, 0),
(null, null, 2, 1, 0, '', 'blocks', 'admin_index', 1, '[{"action":["admin_add"]},{"action":["admin_edit"]},{"action":["admin_delete"]},{"action":["admin_restore"]},{"action":["profile"],"controller":["users"]}]', 1, 1),
(null, null, 9, 1, 0, '', 'users', 'admin_delete', 1, NULL, 1, 1),
(null, null, 1, 1, 0, '', 'articles', 'tag', 1, NULL, 1, 1),
(null, null, 1, 1, 0, '', 'articles', 'admin_restore', 1, NULL, 1, 1),
(null, null, 9, 1, 0, '', 'users', 'admin_restore', 1, NULL, 1, 1),
(null, null, 16, 2, 0, '', 'media', 'view', 1, '[{"action":["view"],"controller":["files"]}]', 2, 2),
(null, null, 16, 1, 0, '', 'media', 'admin_edit', 1, NULL, 1, 1),
(null, null, 16, 1, 0, '', 'media', 'admin_add', 1, NULL, 0, 0),
(null, null, 16, 1, 0, '', 'media', 'admin_index', 1, '[{"action":["admin_add"]},{"action":["admin_edit"]},{"action":["admin_delete"]},{"action":["admin_restore"]},{"action":["view"]},{"action":["profile"],"controller":["users"]}]', 1, 1),
(null, null, 16, 1, 0, '', 'media', 'admin_delete', 1, NULL, 1, 1),
(null, null, 16, 1, 0, '', 'media', 'index', 1, '[{"action":["view"]}]', 2, 2),
(null, null, 8, 1, 0, 'polls', 'polls', 'vote', 1, NULL, 2, 2),
(null, null, 17, 1, 0, 'links', 'links', 'admin_index', 1, '[{"action":["admin_add"]},{"action":["admin_edit"]},{"action":["admin_delete"]},{"action":["admin_restore"]},{"action":["profile"],"controller":["users"]}]', 1, 1),
(null, null, 17, 1, 0, 'links', 'links', 'admin_add', 1, NULL, 0, 0),
(null, null, 17, 1, 0, 'links', 'links', 'admin_edit', 1, NULL, 1, 1),
(null, null, 17, 1, 0, 'links', 'links', 'admin_delete', 1, NULL, 1, 1),
(null, null, 16, 1, 0, '', 'media', 'view', 1, '[{"action":["view"],"controller":["files"]}]', 2, 2),
(null, null, 4, 1, 0, '', 'files', 'view', 1, NULL, 1, 1),
(null, null, 4, 1, 0, '', 'files', 'index', 1, '[{"action":["view"]}]', 1, 1),
(null, null, 9, 1, 0, '', 'users', 'edit', 1, NULL, 1, 2),
(null, null, 9, 1, 0, '', 'users', 'profile', 1, NULL, 1, 1),
(null, null, 20, 1, 0, '', 'comments', 'admin_edit', 1, '[{"action":["admin_edit"],"controller":["articles"]},{"action":["profile"],"controller":["users"]}]', 1, 1),
(null, null, 20, 1, 0, '', 'comments', 'admin_delete', 1, NULL, 1, 1),
(null, null, 20, 1, 0, '', 'comments', 'admin_restore', 1, NULL, 1, 1),
(null, null, 5, 1, 0, '', 'fields', 'admin_delete', 1, NULL, 1, 1),
(null, null, 21, 1, 0, '', 'messages', 'index', 1, NULL, 1, 1),
(null, null, 21, 1, 0, '', 'messages', 'view', 1, NULL, 1, 1),
(null, null, 21, 1, 0, '', 'messages', 'send', 1, NULL, 1, 1),
(null, null, 21, 1, 0, '', 'messages', 'move', 1, NULL, 1, 1),
(null, null, 0, 1, 0, '', 'plugins', 'admin_index', 1, NULL, 2, 2),
(null, null, 19, 1, 0, '', 'cron', 'admin_index', 1, '[{"action":["admin_add"]},{"action":["admin_edit"]},{"action":["admin_delete"]},{"action":["admin_restore"]},{"action":["admin_test"]}]', 1, 1),
(null, null, 10, 1, 0, '', 'pages', 'admin_restore', 1, NULL, 1, 1),
(null, null, 0, 1, 0, '', 'tools', 'admin_optimize_database', 1, '', 2, 2),
(null, null, 0, 1, 0, '', 'tools', 'admin_clear_cache', 1, '', 2, 2),
(null, null, 0, 1, 0, '', 'tools', 'admin_index', 1, '', 2, 2),
(null, null, 11, 1, 0, '', 'roles', 'admin_restore', 1, '', 2, 2),
(null, null, 9, 1, 0, '', 'users', 'admin_ajax_change_user', 1, '', 2, 2),
(null, null, 9, 1, 0, '', 'users', 'ajax_check_user', 1, '', 2, 2),
(null, null, 6, 1, 0, '', 'templates', 'admin_ajax_template_locations', 1, '', 2, 2),
(null, null, 6, 1, 0, '', 'templates', 'admin_ajax_theme_refresh', 1, '', 2, 2),
(null, null, 6, 1, 0, '', 'templates', 'admin_ajax_quick_search', 1, '', 2, 2),
(null, null, 6, 1, 0, '', 'templates', 'admin_ajax_theme_update', 1, '', 2, 2),
(null, null, 0, 1, 0, '', 'permissions', 'admin_ajax_location_list', 1, '', 2, 2),
(null, null, 5, 1, 0, '', 'fields', 'admin_ajax_import', 1, '', 2, 2),
(null, null, 5, 1, 0, '', 'fields', 'admin_ajax_fields', 1, '', 2, 2),
(null, null, 20, 1, 0, '', 'comments', 'ajax_post', 1, '', 1, 1),
(null, null, 2, 1, 0, '', 'blocks', 'admin_ajax_get_model', 1, '', 2, 2),
(null, null, 1, 1, 0, '', 'articles', 'admin_ajax_related_update', 1, '', 2, 2),
(null, null, 1, 1, 0, '', 'articles', 'admin_ajax_related_search', 1, '', 1, 1),
(null, null, 1, 1, 0, '', 'articles', 'admin_delete', 1, '', 1, 1),
(null, null, 2, 1, 0, '', 'blocks', 'admin_edit', 1, '', 1, 0),
(null, null, 2, 1, 0, '', 'blocks', 'admin_delete', 1, '', 1, 1),
(null, null, 2, 1, 0, '', 'blocks', 'admin_restore', 1, '', 1, 1),
(null, null, 3, 1, 0, '', 'categories', 'admin_delete', 1, '', 1, 1),
(null, null, 3, 1, 0, '', 'categories', 'admin_restore', 1, '', 1, 1),
(null, null, 19, 1, 0, '', 'cron', 'admin_add', 1, '', 1, 1),
(null, null, 19, 1, 0, '', 'cron', 'admin_delete', 1, '', 1, 1),
(null, null, 19, 1, 0, '', 'cron', 'admin_edit', 1, '', 1, 1),
(null, null, 19, 1, 0, '', 'cron', 'admin_restore', 1, '', 1, 1),
(null, null, 5, 1, 0, '', 'fields', 'admin_restore', 1, '', 1, 1),
(null, null, 4, 1, 0, '', 'files', 'admin_restore', 1, '', 1, 1),
(null, null, 17, 1, 0, 'links', 'links', 'admin_restore', 1, '', 1, 1),
(null, null, 16, 1, 0, '', 'media', 'admin_restore', 1, '', 1, 1),
(null, null, 8, 2, 0, 'polls', 'polls', 'vote', 1, NULL, 2, 2),
(null, null, 1, 2, 0, '', 'articles', 'tag', 1, NULL, 2, 2),
(null, null, 16, 2, 0, '', 'media', 'index', 1, '[{"action":["view"]}]', 2, 2),
(null, null, 10, 2, 0, '', 'pages', 'display', 1, '[{"action":["view"],"controller":["articles"]}]', 2, 2),
(null, null, 3, 2, 0, '', 'categories', 'view', 1, NULL, 2, 2),
(null, null, 1, 2, 0, '', 'articles', 'view', 1, '[{"action":["ajax_post"], "controller":["comments"]}]', 2, 2),
(null, null, 20, 3, 0, '', 'comments', 'ajax_post', 1, '', 2, 2),
(null, null, 9, 3, 0, '', 'users', 'ajax_check_user', 1, '', 2, 2),
(null, null, 9, 3, 0, '', 'users', 'profile', 1, NULL, 2, 1),
(null, null, 4, 3, 0, '', 'files', 'index', 1, '[{"action":["view"]}]', 1, 1),
(null, null, 4, 3, 0, '', 'files', 'view', 1, NULL, 1, 1),
(null, null, 16, 3, 0, '', 'media', 'view', 1, '[{"action":["view"],"controller":["files"]}]', 2, 2),
(null, null, 8, 3, 0, 'polls', 'polls', 'vote', 1, NULL, 2, 2),
(null, null, 16, 3, 0, '', 'media', 'index', 1, '[{"action":["view"]}]', 2, 2),
(null, null, 1, 3, 0, '', 'articles', 'tag', 1, NULL, 2, 2),
(null, null, 10, 3, 0, '', 'pages', 'display', 1, '[{"action":["view"],"controller":["articles"]}]', 2, 2),
(null, null, 3, 3, 0, '', 'categories', 'view', 1, NULL, 2, 2),
(null, null, 1, 3, 0, '', 'articles', 'view', 1, '[{"action":["ajax_post"], "controller":["comments"]}]', 2, 2),
(null, null, 4, 2, 0, '', 'files', 'view', 1, NULL, 1, 1),
(null, null, 4, 2, 0, '', 'files', 'index', 1, '[{"action":["view"]}]', 1, 1),
(null, null, 9, 2, 0, '', 'users', 'edit', 1, NULL, 1, 2),
(null, null, 9, 2, 0, '', 'users', 'profile', 1, NULL, 1, 2),
(null, null, 21, 2, 0, '', 'messages', 'index', 1, NULL, 1, 1),
(null, null, 21, 2, 0, '', 'messages', 'view', 1, NULL, 1, 1),
(null, null, 21, 2, 0, '', 'messages', 'send', 1, NULL, 1, 1),
(null, null, 21, 2, 0, '', 'messages', 'move', 1, NULL, 1, 1),
(null, null, 9, 2, 0, '', 'users', 'ajax_check_user', 1, '', 2, 2),
(null, null, 20, 2, 0, '', 'comments', 'ajax_post', 1, '', 1, 1),
(null, null, 8, 1, 0, 'polls', 'polls', 'ajax_view_poll', 1, '[{"action":["vote"]}]', 1, 1),
(null, null, 8, 1, 0, 'polls', 'polls', 'ajax_results', 1, '[{"action":["vote"]}]', 1, 1),
(null, null, 8, 2, 0, 'polls', 'polls', 'ajax_results', 1, '[{"action":["vote"]}]', 2, 1),
(null, null, 8, 2, 0, 'polls', 'polls', 'ajax_view_poll', 1, '[{"action":["vote"]}]', 2, 1),
(null, null, 8, 3, 0, 'polls', 'polls', 'ajax_results', 1, '[{"action":["vote"]}]', 2, 1),
(null, null, 8, 3, 0, 'polls', 'polls', 'ajax_view_poll', 1, '[{"action":["vote"]}]', 2, 1),
(null, null, 9, 4, 0, '', 'users', 'admin_index', 1, '[{"action":["admin_add"]},{"action":["admin_edit"]},{"action":["admin_delete"]},{"action":["admin_restore"]},{"action":["profile"]},{"action":["admin_ajax_change_user"]}]', 1, 1),
(null, null, 11, 4, 0, '', 'roles', 'admin_index', 0, '[{"action":["admin_add"]},{"action":["admin_edit"]},{"action":["admin_delete"]},{"action":["admin_restore"]}]', 2, 2),
(null, null, 11, 4, 0, '', 'roles', 'admin_add', 0, NULL, 0, 0),
(null, null, 11, 4, 0, '', 'roles', 'admin_edit', 0, NULL, 2, 2),
(null, null, 11, 4, 0, '', 'roles', 'admin_delete', 0, NULL, 2, 2),
(null, null, 0, 4, 0, '', 'permissions', 'admin_add', 0, NULL, 0, 0),
(null, null, 6, 4, 0, '', 'templates', 'admin_restore', 0, '', 0, 0),
(null, null, 1, 4, 0, '', 'articles', 'admin_index', 1, '[{"action":["admin_add"]},{"action":["admin_edit"]},{"action":["admin_delete"]},{"action":["admin_restore"]},{"action":["view"]},{"action":["profile"],"controller":["users"]}]', 1, 0),
(null, null, 1, 4, 0, '', 'articles', 'admin_add', 1, NULL, 0, 0),
(null, null, 1, 4, 0, '', 'articles', 'admin_edit', 1, NULL, 1, 0),
(null, null, 3, 4, 0, '', 'categories', 'admin_index', 1, '[{"action":["admin_add"]},{"action":["admin_edit"]},{"action":["admin_delete"]},{"action":["admin_restore"]},{"action":["view"]},{"action":["profile"],"controller":["users"]}]', 1, 1),
(null, null, 5, 4, 0, '', 'fields', 'admin_index', 1, '[{"action":["admin_add"]},{"action":["admin_edit"]},{"action":["admin_delete"]},{"action":["admin_restore"]},{"action":["profile"],"controller":["users"]}]', 1, 1),
(null, null, 10, 4, 0, '', 'pages', 'admin_index', 1, '[{"action":["admin_add"]},{"action":["admin_edit"]},{"action":["admin_delete"]},{"action":["admin_restore"]},{"action":["display"]},{"action":["profile"],"controller":["users"]}]', 1, 1),
(null, null, 12, 4, 0, '', 'settings', 'admin_index', 0, '[{"action":["admin_add"]},{"action":["admin_edit"]},{"action":["admin_delete"]},{"action":["admin_restore"]}]', 0, 0),
(null, null, 8, 4, 0, 'polls', 'polls', 'admin_restore', 1, '', 1, 0),
(null, null, 10, 4, 0, '', 'pages', 'admin_edit', 1, NULL, 1, 0),
(null, null, 10, 4, 0, '', 'pages', 'admin_add', 1, NULL, 0, 0),
(null, null, 10, 4, 0, '', 'pages', 'admin_delete', 1, NULL, 1, 0),
(null, null, 12, 4, 0, '', 'settings', 'admin_add', 0, NULL, 0, 0),
(null, null, 12, 4, 0, '', 'settings', 'admin_edit', 0, NULL, 0, 0),
(null, null, 12, 4, 0, '', 'settings', 'admin_delete', 0, NULL, 0, 0),
(null, null, 13, 4, 0, '', 'setting_values', 'admin_add', 0, NULL, 0, 0),
(null, null, 13, 4, 0, '', 'setting_values', 'admin_edit', 0, NULL, 0, 0),
(null, null, 5, 4, 0, '', 'fields', 'admin_add', 1, NULL, 0, 0),
(null, null, 5, 4, 0, '', 'fields', 'admin_edit', 1, NULL, 1, 0),
(null, null, 1, 4, 0, '', 'articles', 'view', 1, '[{"action":["ajax_post"], "controller":["comments"]},{"action":["admin_edit"], "controller":["comments"]},{"action":["admin_delete"], "controller":["comments"]}]', 1, 1),
(null, null, 9, 4, 0, '', 'users', 'admin_add', 0, NULL, 0, 0),
(null, null, 9, 4, 0, '', 'users', 'admin_edit', 0, NULL, 0, 0),
(null, null, 8, 4, 0, 'polls', 'polls', 'admin_index', 1, '[{"action":["admin_add"]},{"action":["admin_edit"]},{"action":["admin_delete"]},{"action":["admin_restore"]},{"action":["profile"],"controller":["users"]}]', 1, 1),
(null, null, 8, 4, 0, 'polls', 'polls', 'admin_add', 1, NULL, 0, 0),
(null, null, 8, 4, 0, 'polls', 'polls', 'admin_delete', 1, NULL, 1, 0),
(null, null, 8, 4, 0, 'polls', 'polls', 'admin_edit', 1, NULL, 1, 1),
(null, null, 3, 4, 0, '', 'categories', 'admin_add', 0, NULL, 0, 0),
(null, null, 3, 4, 0, '', 'categories', 'admin_edit', 0, NULL, 0, 0),
(null, null, 3, 4, 0, '', 'categories', 'view', 1, NULL, 1, 1),
(null, null, 10, 4, 0, '', 'pages', 'display', 1, '[{"action":["view"],"controller":["articles"]}]', 2, 2),
(null, null, 4, 4, 0, '', 'files', 'admin_index', 1, '[{"action":["admin_add"]},{"action":["admin_add_folder"]},{"action":["admin_edit"]},{"action":["admin_delete"]},{"action":["admin_restore"]},{"action":["view"]}]', 1, 0),
(null, null, 4, 4, 0, '', 'files', 'admin_add', 1, NULL, 0, 0),
(null, null, 4, 4, 0, '', 'files', 'admin_edit', 1, NULL, 1, 0),
(null, null, 4, 4, 0, '', 'files', 'admin_delete', 1, NULL, 1, 0),
(null, null, 6, 4, 0, '', 'templates', 'admin_index', 0, '[{"action":["admin_add"]},{"action":["admin_edit"]},{"action":["admin_delete"]},{"action":["admin_restore"]}]', 0, 0),
(null, null, 6, 4, 0, '', 'templates', 'admin_add', 0, NULL, 0, 0),
(null, null, 6, 4, 0, '', 'templates', 'admin_edit', 0, NULL, 0, 0),
(null, null, 6, 4, 0, '', 'templates', 'admin_delete', 0, NULL, 0, 0),
(null, null, 7, 4, 0, '', 'themes', 'admin_add', 0, NULL, 0, 0),
(null, null, 7, 4, 0, '', 'themes', 'admin_edit', 0, '[{"action":["admin_asset_add"]},{"action":["admin_asset_edit"]},{"action":["admin_asset_delete"]}]', 0, 0),
(null, null, 7, 4, 0, '', 'themes', 'admin_delete', 0, NULL, 0, 0),
(null, null, 7, 4, 0, '', 'themes', 'admin_restore', 0, '', 0, 0),
(null, null, 2, 4, 0, '', 'blocks', 'admin_add', 1, NULL, 0, 0),
(null, null, 2, 4, 0, '', 'blocks', 'admin_index', 1, '[{"action":["admin_add"]},{"action":["admin_edit"]},{"action":["admin_delete"]},{"action":["admin_restore"]},{"action":["profile"],"controller":["users"]}]', 1, 1),
(null, null, 9, 4, 0, '', 'users', 'admin_delete', 0, NULL, 0, 0),
(null, null, 1, 4, 0, '', 'articles', 'tag', 1, NULL, 1, 1),
(null, null, 1, 4, 0, '', 'articles', 'admin_restore', 1, NULL, 1, 0),
(null, null, 9, 4, 0, '', 'users', 'admin_restore', 0, NULL, 0, 0),
(null, null, 16, 4, 0, '', 'media', 'admin_edit', 1, NULL, 1, 0),
(null, null, 16, 4, 0, '', 'media', 'admin_add', 1, NULL, 0, 0),
(null, null, 16, 4, 0, '', 'media', 'admin_index', 1, '[{"action":["admin_add"]},{"action":["admin_edit"]},{"action":["admin_delete"]},{"action":["admin_restore"]},{"action":["view"]},{"action":["profile"],"controller":["users"]}]', 1, 1),
(null, null, 16, 4, 0, '', 'media', 'admin_delete', 1, NULL, 1, 0),
(null, null, 16, 4, 0, '', 'media', 'index', 1, '[{"action":["view"]}]', 2, 2),
(null, null, 8, 4, 0, 'polls', 'polls', 'vote', 1, NULL, 2, 2),
(null, null, 17, 4, 0, 'links', 'links', 'admin_index', 1, '[{"action":["admin_add"]},{"action":["admin_edit"]},{"action":["admin_delete"]},{"action":["admin_restore"]},{"action":["profile"],"controller":["users"]}]', 1, 1),
(null, null, 17, 4, 0, 'links', 'links', 'admin_add', 1, NULL, 0, 0),
(null, null, 17, 4, 0, 'links', 'links', 'admin_edit', 1, NULL, 1, 0),
(null, null, 17, 4, 0, 'links', 'links', 'admin_delete', 1, NULL, 1, 0),
(null, null, 16, 4, 0, '', 'media', 'view', 1, '[{"action":["view"],"controller":["files"]}]', 2, 2),
(null, null, 4, 4, 0, '', 'files', 'view', 1, NULL, 1, 1),
(null, null, 4, 4, 0, '', 'files', 'index', 1, '[{"action":["view"]}]', 1, 1),
(null, null, 9, 4, 0, '', 'users', 'edit', 1, NULL, 1, 2),
(null, null, 9, 4, 0, '', 'users', 'profile', 1, NULL, 1, 1),
(null, null, 20, 4, 0, '', 'comments', 'admin_edit', 1, '[{"action":["admin_edit"],"controller":["articles"]},{"action":["profile"],"controller":["users"]}]', 1, 1),
(null, null, 20, 4, 0, '', 'comments', 'admin_delete', 1, NULL, 1, 1),
(null, null, 20, 4, 0, '', 'comments', 'admin_restore', 1, NULL, 1, 1),
(null, null, 5, 4, 0, '', 'fields', 'admin_delete', 1, NULL, 1, 0),
(null, null, 21, 4, 0, '', 'messages', 'index', 1, NULL, 1, 1),
(null, null, 21, 4, 0, '', 'messages', 'view', 1, NULL, 1, 1),
(null, null, 21, 4, 0, '', 'messages', 'send', 1, NULL, 1, 1),
(null, null, 21, 4, 0, '', 'messages', 'move', 1, NULL, 1, 1),
(null, null, 0, 4, 0, '', 'plugins', 'admin_index', 1, NULL, 2, 2),
(null, null, 19, 4, 0, '', 'cron', 'admin_index', 0, '[{"action":["admin_add"]},{"action":["admin_edit"]},{"action":["admin_delete"]},{"action":["admin_restore"]},{"action":["admin_test"]}]', 0, 0),
(null, null, 10, 4, 0, '', 'pages', 'admin_restore', 1, NULL, 1, 0),
(null, null, 0, 4, 0, '', 'tools', 'admin_optimize_database', 1, '', 2, 2),
(null, null, 0, 4, 0, '', 'tools', 'admin_clear_cache', 1, '', 2, 2),
(null, null, 0, 4, 0, '', 'tools', 'admin_index', 1, '', 2, 2),
(null, null, 11, 4, 0, '', 'roles', 'admin_restore', 0, '', 2, 2),
(null, null, 9, 4, 0, '', 'users', 'admin_ajax_change_user', 1, '', 2, 2),
(null, null, 9, 4, 0, '', 'users', 'ajax_check_user', 1, '', 2, 2),
(null, null, 6, 4, 0, '', 'templates', 'admin_ajax_template_locations', 0, '', 2, 2),
(null, null, 6, 4, 0, '', 'templates', 'admin_ajax_theme_refresh', 0, '', 2, 2),
(null, null, 6, 4, 0, '', 'templates', 'admin_ajax_quick_search', 0, '', 2, 2),
(null, null, 6, 4, 0, '', 'templates', 'admin_ajax_theme_update', 0, '', 2, 2),
(null, null, 0, 4, 0, '', 'permissions', 'admin_ajax_location_list', 1, '', 2, 2),
(null, null, 5, 4, 0, '', 'fields', 'admin_ajax_import', 1, '', 2, 2),
(null, null, 5, 4, 0, '', 'fields', 'admin_ajax_fields', 1, '', 2, 2),
(null, null, 20, 4, 0, '', 'comments', 'ajax_post', 1, '', 1, 1),
(null, null, 2, 4, 0, '', 'blocks', 'admin_ajax_get_model', 1, '', 2, 2),
(null, null, 1, 4, 0, '', 'articles', 'admin_ajax_related_update', 1, '', 2, 2),
(null, null, 1, 4, 0, '', 'articles', 'admin_ajax_related_search', 1, '', 1, 1),
(null, null, 1, 4, 0, '', 'articles', 'admin_delete', 1, '', 1, 0),
(null, null, 2, 4, 0, '', 'blocks', 'admin_edit', 1, '', 1, 0),
(null, null, 2, 4, 0, '', 'blocks', 'admin_delete', 1, '', 1, 0),
(null, null, 2, 4, 0, '', 'blocks', 'admin_restore', 1, '', 1, 0),
(null, null, 3, 4, 0, '', 'categories', 'admin_delete', 0, '', 0, 0),
(null, null, 3, 4, 0, '', 'categories', 'admin_restore', 0, '', 0, 0),
(null, null, 19, 4, 0, '', 'cron', 'admin_add', 0, '', 1, 1),
(null, null, 19, 4, 0, '', 'cron', 'admin_delete', 0, '', 0, 0),
(null, null, 19, 4, 0, '', 'cron', 'admin_edit', 0, '', 0, 0),
(null, null, 19, 4, 0, '', 'cron', 'admin_restore', 0, '', 0, 0),
(null, null, 5, 4, 0, '', 'fields', 'admin_restore', 0, '', 0, 0),
(null, null, 4, 4, 0, '', 'files', 'admin_restore', 1, '', 1, 0),
(null, null, 17, 4, 0, 'links', 'links', 'admin_restore', 1, '', 1, 0),
(null, null, 16, 4, 0, '', 'media', 'admin_restore', 1, '', 1, 0),
(null, null, 8, 4, 0, 'polls', 'polls', 'ajax_view_poll', 1, '[{"action":["vote"]}]', 1, 1),
(null, null, 8, 4, 0, 'polls', 'polls', 'ajax_results', 1, '[{"action":["vote"]}]', 1, 1),
(null, null, 10, 1, 0, '', 'pages', 'admin', 1, NULL, 2, 2),
(null, null, 10, 4, 0, '', 'pages', 'admin', 1, NULL, 2, 2),
(null, null, 0, 4, 0, '', 'plugins', 'admin_settings', 0, NULL, 2, 2),
(null, null, 0, 1, 0, '', 'plugins', 'admin_settings', 1, NULL, 2, 2),
(null, null, 0, 1, 0, '', 'tools', 'admin_convert_wordpress', 1, '', 2, 2),
(null, null, 0, 4, 0, '', 'tools', 'admin_convert_wordpress', 0, '', 2, 2),
(null, null, 7, 1, 0, '', 'themes', 'admin_asset_delete', 1, '', 0, 1),
(null, null, 7, 1, 0, '', 'themes', 'admin_asset_add', 1, '', 0, 1),
(null, null, 7, 1, 0, '', 'themes', 'admin_asset_edit', 1, '', 0, 1),
(null, null, 7, 4, 0, '', 'themes', 'admin_asset_delete', 0, '', 0, 0),
(null, null, 7, 4, 0, '', 'themes', 'admin_asset_add', 0, '', 0, 0),
(null, null, 7, 4, 0, '', 'themes', 'admin_asset_edit', 0, '', 0, 0),
(null, null, 12, 4, 0, '', 'settings', 'admin_restore', 0, NULL, 0, 0),
(null, null, 12, 1, 0, '', 'settings', 'admin_restore', 1, NULL, 1, 1),
(null, null, NULL, 1, 0, '', 'plugins', 'admin_assets', 1, '', 2, 2),
(null, null, NULL, 4, 0, '', 'plugins', 'admin_assets', 0, '', 2, 2),
(null, null, NULL, 1, 0, '', 'plugins', 'admin_permissions', 1, '', 2, 2),
(null, null, NULL, 4, 0, '', 'plugins', 'admin_permissions', 0, '', 2, 2),
(null, null, 0, 1, 0, '', 'tools', 'admin_convert_adaptcms', 1, '', 2, 2),
(null, null, 0, 4, 0, '', 'tools', 'admin_convert_adaptcms', 0, '', 2, 2),
(null, null, 12, 1, 0, '', 'settings', 'admin_restore', 0, NULL, 2, 2),
(null, null, 12, 4, 0, '', 'settings', 'admin_restore', 0, NULL, 2, 2),
(null, null, NULL, 1, 0, '', 'menus', 'admin_restore', 1, '', 1, 1),
(null, null, NULL, 1, 0, '', 'menus', 'admin_delete', 1, '', 1, 1),
(null, null, NULL, 1, 0, '', 'menus', 'admin_edit', 1, '', 1, 1),
(null, null, NULL, 1, 0, '', 'menus', 'admin_add', 1, '', 0, 0),
(null, null, NULL, 1, 0, '', 'menus', 'admin_index', 1, '[{"action":["admin_add"]},{"action":["admin_edit"]},{"action":["admin_delete"]},{"action":["admin_restore"]},{"action":["profile"],"controller":["users"]}]', 1, 1),
(null, null, NULL, 4, 0, '', 'menus', 'admin_restore', 1, '', 1, 1),
(null, null, NULL, 4, 0, '', 'menus', 'admin_delete', 1, '', 1, 1),
(null, null, NULL, 4, 0, '', 'menus', 'admin_edit', 1, '', 1, 1),
(null, null, NULL, 4, 0, '', 'menus', 'admin_add', 1, '', 0, 0),
(null, null, NULL, 4, 0, '', 'menus', 'admin_index', 1, '[{"action":["admin_add"]},{"action":["admin_edit"]},{"action":["admin_delete"]},{"action":["admin_restore"]},{"action":["profile"],"controller":["users"]}]', 1, 1),
(null, null, NULL, 1, 0, '', 'field_types', 'admin_restore', 1, '', 1, 1),
(null, null, NULL, 1, 0, '', 'field_types', 'admin_delete', 1, '', 1, 1),
(null, null, NULL, 1, 0, '', 'field_types', 'admin_edit', 1, '', 1, 1),
(null, null, NULL, 1, 0, '', 'field_types', 'admin_add', 1, '', 0, 0),
(null, null, NULL, 1, 0, '', 'field_types', 'admin_index', 1, '[{"action":["admin_add"]},{"action":["admin_edit"]},{"action":["admin_delete"]},{"action":["admin_restore"]},{"action":["profile"],"controller":["users"]}]', 1, 1),
(null, null, NULL, 4, 0, '', 'field_types', 'admin_restore', 1, '', 1, 1),
(null, null, NULL, 4, 0, '', 'field_types', 'admin_delete', 1, '', 1, 1),
(null, null, NULL, 4, 0, '', 'field_types', 'admin_edit', 1, '', 1, 1),
(null, null, NULL, 4, 0, '', 'field_types', 'admin_add', 1, '', 0, 0),
(null, null, NULL, 4, 0, '', 'field_types', 'admin_index', 1, '[{"action":["admin_add"]},{"action":["admin_edit"]},{"action":["admin_delete"]},{"action":["admin_restore"]},{"action":["profile"],"controller":["users"]}]', 1, 1),
(null, null, NULL, 1, 0, '', 'install', 'install_plugin', 1, '', 2, 2),
(null, null, NULL, 1, 0, '', 'install', 'uninstall_plugin', 1, '', 2, 2),
(null, null, NULL, 1, 0, '', 'install', 'upgrade_plugin', 1, '', 2, 2),
(null, null, NULL, 1, 0, '', 'install', 'install_theme', 1, '', 2, 2),
(null, null, NULL, 1, 0, '', 'install', 'uninstall_theme', 1, '', 2, 2),
(null, null, NULL, 1, 0, '', 'install', 'upgrade_theme', 1, '', 2, 2),
(null, null, NULL, 1, 0, '', 'install', 'upgrade', 1, '', 2, 2),
(null, null, NULL, 4, 0, '', 'install', 'install_plugin', 0, '', 2, 2),
(null, null, NULL, 4, 0, '', 'install', 'uninstall_plugin', 0, '', 2, 2),
(null, null, NULL, 4, 0, '', 'install', 'upgrade_plugin', 0, '', 2, 2),
(null, null, NULL, 4, 0, '', 'install', 'install_theme', 0, '', 2, 2),
(null, null, NULL, 4, 0, '', 'install', 'uninstall_theme', 0, '', 2, 2),
(null, null, NULL, 4, 0, '', 'install', 'upgrade_theme', 0, '', 2, 2),
(null, null, NULL, 4, 0, '', 'install', 'upgrade', 0, '', 2, 2),
(null, NULL, 22, 1, 0, 'google_maps', 'google_maps', 'admin_index', 1, '[{"action":["admin_add"]},{"action":["admin_edit"]},{"action":["admin_delete"]},{"action":["admin_restore"]},{"action":["profile"],"controller":["users"]}]', 1, 1),
(null, NULL, 22, 1, 0, 'google_maps', 'google_maps', 'admin_add', 1, '', 1, 1),
(null, NULL, 22, 1, 0, 'google_maps', 'google_maps', 'admin_edit', 1, '', 1, 1),
(null, NULL, 22, 1, 0, 'google_maps', 'google_maps', 'admin_delete', 1, '', 1, 1),
(null, NULL, 22, 1, 0, 'google_maps', 'google_maps', 'admin_restore', 1, '', 1, 1),
(null, NULL, 22, 2, 0, 'google_maps', 'google_maps', 'admin_index', 0, '[{"action":["admin_add"]},{"action":["admin_edit"]},{"action":["admin_delete"]},{"action":["admin_restore"]},{"action":["profile"],"controller":["users"]}]', 0, 0),
(null, NULL, 22, 2, 0, 'google_maps', 'google_maps', 'admin_add', 0, '', 0, 0),
(null, NULL, 22, 2, 0, 'google_maps', 'google_maps', 'admin_edit', 0, '', 0, 0),
(null, NULL, 22, 2, 0, 'google_maps', 'google_maps', 'admin_delete', 0, '', 0, 0),
(null, NULL, 22, 2, 0, 'google_maps', 'google_maps', 'admin_restore', 0, '', 0, 0),
(null, NULL, 22, 3, 0, 'google_maps', 'google_maps', 'admin_index', 0, '[{"action":["admin_add"]},{"action":["admin_edit"]},{"action":["admin_delete"]},{"action":["admin_restore"]},{"action":["profile"],"controller":["users"]}]', 0, 0),
(null, NULL, 22, 3, 0, 'google_maps', 'google_maps', 'admin_add', 0, '', 0, 0),
(null, NULL, 22, 3, 0, 'google_maps', 'google_maps', 'admin_edit', 0, '', 0, 0),
(null, NULL, 22, 3, 0, 'google_maps', 'google_maps', 'admin_delete', 0, '', 0, 0),
(null, NULL, 22, 3, 0, 'google_maps', 'google_maps', 'admin_restore', 0, '', 0, 0),
(null, NULL, 22, 4, 0, 'google_maps', 'google_maps', 'admin_index', 0, '[{"action":["admin_add"]},{"action":["admin_edit"]},{"action":["admin_delete"]},{"action":["admin_restore"]},{"action":["profile"],"controller":["users"]}]', 0, 0),
(null, NULL, 22, 4, 0, 'google_maps', 'google_maps', 'admin_add', 0, '', 0, 0),
(null, NULL, 22, 4, 0, 'google_maps', 'google_maps', 'admin_edit', 0, '', 0, 0),
(null, NULL, 22, 4, 0, 'google_maps', 'google_maps', 'admin_delete', 0, '', 0, 0),
(null, NULL, 22, 4, 0, 'google_maps', 'google_maps', 'admin_restore', 0, '', 0, 0),
(null, NULL, 21, 4, 0, 'adaptbb', 'forum_categories', 'admin_delete', 0, '', 0, 0),
(null, NULL, 21, 4, 0, 'adaptbb', 'forum_categories', 'admin_edit', 0, '', 0, 0),
(null, NULL, 21, 4, 0, 'adaptbb', 'forum_categories', 'admin_add', 0, '', 0, 0),
(null, NULL, 21, 4, 0, 'adaptbb', 'forum_categories', 'admin_index', 0, '[{"action":["admin_add"]},{"action":["admin_edit"]},{"action":["admin_delete"]},{"action":["admin_restore"]},{"action":["admin_index"],"controller":["forums"]}]', 0, 0),
(null, NULL, 21, 4, 0, 'adaptbb', 'forum_posts', 'ajax_post', 1, '', 0, 0),
(null, NULL, 21, 4, 0, 'adaptbb', 'forum_topics', 'add', 1, '', 0, 0),
(null, NULL, 21, 4, 0, 'adaptbb', 'forum_topics', 'view', 1, '[{"action":["change_status"]},{"action":["edit"]},{"action":["delete"]},{"action":["edit"],"controller":["forum_posts"]},{"action":["delete"],"controller":["forum_posts"]},{"action":["add"],"controller":["forum_posts"]}]', 0, 0),
(null, NULL, 21, 4, 0, 'adaptbb', 'forums', 'view', 1, '', 0, 0),
(null, NULL, 21, 4, 0, 'adaptbb', 'forums', 'index', 1, '', 0, 0),
(null, NULL, 21, 3, 0, 'adaptbb', 'forum_topics', 'view', 1, '[{"action":["change_status"]},{"action":["edit"]},{"action":["delete"]},{"action":["ajax_edit"],"controller":["forum_posts"]},{"action":["delete"],"controller":["forum_posts"]},{"action":["ajax_post"],"controller":["forum_posts"]}]', 2, 2),
(null, NULL, 21, 3, 0, 'adaptbb', 'forums', 'view', 1, '[{"action":["add"],"controller":["forum_topics"]},{"action":["view"],"controller":["forum_topics"]}]', 2, 2),
(null, NULL, 21, 3, 0, 'adaptbb', 'forums', 'index', 1, '[{"action":["profile"],"controller":["users"],"plugin":null}]', 2, 2),
(null, NULL, 21, 2, 0, 'adaptbb', 'forum_posts', 'ajax_post', 1, '', 2, 2),
(null, NULL, 21, 2, 0, 'adaptbb', 'forum_topics', 'add', 1, '', 2, 2),
(null, NULL, 21, 2, 0, 'adaptbb', 'forum_topics', 'view', 1, '[{"action":["change_status"]},{"action":["edit"]},{"action":["delete"]},{"action":["edit"],"controller":["forum_posts"]},{"action":["delete"],"controller":["forum_posts"]},{"action":["add"],"controller":["forum_posts"]}]', 2, 2),
(null, NULL, 21, 2, 0, 'adaptbb', 'forums', 'view', 1, '', 2, 2),
(null, NULL, 21, 2, 0, 'adaptbb', 'forums', 'index', 1, '', 2, 2),
(null, NULL, 21, 1, 0, 'adaptbb', 'forums', 'admin_ajax_forums', 1, '', 1, 1),
(null, NULL, 21, 1, 0, 'adaptbb', 'forum_posts', 'ajax_post', 1, '', 1, 1),
(null, NULL, 21, 1, 0, 'adaptbb', 'forum_categories', 'admin_index', 1, '[{"action":["admin_add"]},{"action":["admin_edit"]},{"action":["admin_delete"]},{"action":["admin_restore"]},{"action":["admin_index"],"controller":["forums"]},{"action":["profile"],"controller":["users"]}]', 1, 1),
(null, NULL, 21, 1, 0, 'adaptbb', 'forum_categories', 'admin_add', 1, '', 1, 1),
(null, NULL, 21, 1, 0, 'adaptbb', 'forum_categories', 'admin_edit', 1, '', 1, 1),
(null, NULL, 21, 1, 0, 'adaptbb', 'forum_categories', 'admin_delete', 1, '', 1, 1),
(null, NULL, 21, 1, 0, 'adaptbb', 'forum_categories', 'admin_restore', 1, '', 1, 1),
(null, NULL, 21, 1, 0, 'adaptbb', 'forums', 'admin_index', 1, '[{"action":["admin_add"]},{"action":["admin_edit"]},{"action":["admin_delete"]},{"action":["admin_restore"]},{"action":["admin_index"],"controller":["forum_categories"]},{"action":["profile"],"controller":["users"]},{"controller":["forum_categories"],"action":["admin_edit"]}]', 1, 1),
(null, NULL, 21, 1, 0, 'adaptbb', 'forums', 'admin_add', 1, '', 1, 1),
(null, NULL, 21, 1, 0, 'adaptbb', 'forums', 'admin_edit', 1, '', 1, 1),
(null, NULL, 21, 1, 0, 'adaptbb', 'forums', 'admin_delete', 1, '', 1, 1),
(null, NULL, 21, 1, 0, 'adaptbb', 'forums', 'admin_restore', 1, '', 1, 1),
(null, NULL, 21, 1, 0, 'adaptbb', 'forum_topics', 'add', 1, '[{"action":["add_sticky"]},{"action":["add_announcement"]}]', 1, 1),
(null, NULL, 21, 1, 0, 'adaptbb', 'forum_topics', 'view', 1, '[{"action":["change_status"]},{"action":["edit"]},{"action":["delete"]},{"action":["ajax_edit"],"controller":["forum_posts"]},{"action":["delete"],"controller":["forum_posts"]},{"action":["ajax_post"],"controller":["forum_posts"]}]', 1, 1),
(null, NULL, 21, 1, 0, 'adaptbb', 'forums', 'view', 1, '[{"action":["add"],"controller":["forum_topics"]},{"action":["view"],"controller":["forum_topics"]}]', 1, 1),
(null, NULL, 21, 1, 0, 'adaptbb', 'forums', 'index', 1, '[{"action":["profile"],"controller":["users"],"plugin":null}]', 1, 1),
(null, NULL, 21, 4, 0, 'adaptbb', 'forum_categories', 'admin_restore', 0, '', 0, 0),
(null, NULL, 21, 4, 0, 'adaptbb', 'forums', 'admin_index', 0, '[{"action":["admin_add"]},{"action":["admin_edit"]},{"action":["admin_delete"]},{"action":["admin_restore"]},{"action":["admin_index"],"controller":["forum_categories"]}]', 0, 0),
(null, NULL, 21, 4, 0, 'adaptbb', 'forums', 'admin_add', 0, '', 0, 0),
(null, NULL, 21, 4, 0, 'adaptbb', 'forums', 'admin_edit', 0, '', 0, 0),
(null, NULL, 21, 4, 0, 'adaptbb', 'forums', 'admin_delete', 0, '', 0, 0),
(null, NULL, 21, 4, 0, 'adaptbb', 'forums', 'admin_restore', 0, '', 0, 0),
(null, NULL, 21, 4, 0, 'adaptbb', 'forums', 'admin_ajax_forums', 0, '', 0, 0),
(null, NULL, 21, 1, 0, 'adaptbb', 'forum_topics', 'edit', 1, '[{"action":["change_status"]},{"action":["add_sticky"]},{"action":["add_announcement"]}]', 1, 1),
(null, NULL, 21, 1, 0, 'adaptbb', 'forum_topics', 'delete', 1, '', 1, 1),
(null, NULL, 21, 1, 0, 'adaptbb', 'forum_topics', 'change_status', 1, '', 1, 1),
(null, NULL, 21, 1, 0, 'adaptbb', 'forum_posts', 'ajax_edit', 1, '', 1, 1),
(null, NULL, 21, 1, 0, 'adaptbb', 'forum_posts', 'delete', 1, '', 1, 1),
(null, 'Create Sticky Topic', 21, 1, 0, 'adaptbb', 'forum_topics', 'add_sticky', null, NULL, 1, 1),
(null, 'Create Announcement Topic', 21, 1, 0, 'adaptbb', 'forum_topics', 'add_announcement', null, NULL, 1, 1),
(null, NULL, 19, 1, 0, '', 'cron', 'admin_test', 1, '', 2, 2),
(null, NULL, 19, 4, 0, '', 'cron', 'admin_test', 0, '', 2, 2),
(null, NULL, 17, 1, 0, 'links', 'links', 'apply', 1, '', 2, 2),
(null, NULL, 17, 2, 0, 'links', 'links', 'apply', 1, '', 2, 2),
(null, NULL, 17, 3, 0, 'links', 'links', 'apply', 1, '', 2, 2),
(null, NULL, 17, 4, 0, 'links', 'links', 'apply', 1, '', 2, 2),
(null, NULL, 8, 1, 0, 'polls', 'polls', 'all', 1, '[{"action":["vote"]}]', 1, 1),
(null, NULL, 8, 2, 0, 'polls', 'polls', 'all', 1, '[{"action":["vote"]}]', 2, 2),
(null, NULL, 8, 3, 0, 'polls', 'polls', 'all', 1, '[{"action":["vote"]}]', 2, 2),
(null, NULL, 8, 4, 0, 'polls', 'polls', 'all', 1, '[{"action":["vote"]}]', 1, 1),
(null, NULL, 20, 1, 0, '', 'comments', 'admin_index', 1, '[{"action":["admin_edit"]},{"action":["admin_delete"]},{"action":["admin_restore"]},{"action":["admin_edit"],"controller":["articles"]},{"action":["profile"],"controller":["users"]}]', 1, 1),
(null, NULL, 20, 1, 0, '', 'comments', 'admin_index', 4, '[{"action":["admin_edit"]},{"action":["admin_delete"]},{"action":["admin_restore"]},{"action":["admin_edit"],"controller":["articles"]},{"action":["profile"],"controller":["users"]}]', 1, 1),
(null, NULL, 4, 1, 0, '', 'files', 'admin_add_folder', 1, '[{"action":["admin_index"]}]', 2, 2),
(null, NULL, 4, 4, 0, '', 'files', 'admin_add_folder', 1, '[{"action":["admin_index"]}]', 2, 2),
(null, NULL, 9, 1, 0, '', 'users', 'ajax_quick_search', 1, null, 2, 2),
(null, NULL, 9, 2, 0, '', 'users', 'ajax_quick_search', 1, null, 2, 2),
(null, NULL, 9, 4, 0, '', 'users', 'ajax_quick_search', 1, null, 2, 2),
(null, NULL, 6, 1, 0, '', 'templates', 'admin_global_tags', 1, '', 2, 2),
(null, NULL, 6, 4, 0, '', 'templates', 'admin_global_tags', 0, '', 2, 2),
(null, null, 0, 1, 0, '', 'tools', 'admin_convert_onecms', 1, '', 2, 2),
(null, null, 0, 4, 0, '', 'tools', 'admin_convert_onecms', 0, '', 2, 2);
-- --------------------------------------------------------
INSERT INTO `{prefix}plugin_adaptbb_forums` (`id`, `title`, `slug`, `category_id`, `description`, `status`, `num_posts`, `num_topics`, `ord`, `user_id`, `icon_url`, `created`, `modified`, `deleted_time`) VALUES
(1, 'Off Topic', 'off-topic', 1, '<p>All discussions go here.</p>', 1, 0, 0, 0, 1, '', '{date}', '{date}', '0000-00-00 00:00:00');
-- --------------------------------------------------------
INSERT INTO `{prefix}plugin_adaptbb_forum_categories` (`id`, `title`, `slug`, `ord`, `user_id`, `created`, `modified`, `deleted_time`) VALUES
(1, 'General', 'general', 0, 1, '{date}', '{date}', '0000-00-00 00:00:00');
-- --------------------------------------------------------
INSERT INTO `{prefix}plugin_google_maps` (`id`, `user_id`, `title`, `slug`, `map_type`, `locations`, `options`, `created`, `modified`, `deleted_time`) VALUES
(1, 1, 'White House', 'white-house', 'basic', '[{"address":"1600 Pennsylvania Ave Nw, Washington","color":"blue","size":"normal","content":"This is the White House.","latitude":"38.897096","longitude":"-77.03654499999999"},{"address":"300 Maryland Ave Sw, Washington","color":"orange","size":"normal","content":"The Smithsonian Institution.","latitude":"38.8881691","longitude":"-77.01522039999998"}]', '{"center":{"address":"1600 Pennsylvania Ave Nw, Washington","latitude":"38.897096","longitude":"-77.036545"},"zoom":"14","width":"610","height":"300"}', '{date}', '{date}', '0000-00-00 00:00:00');
-- --------------------------------------------------------
INSERT INTO `{prefix}plugin_links` (`id`, `file_id`, `title`, `url`, `link_title`, `link_target`, `views`, `user_id`, `created`, `modified`, `deleted_time`) VALUES
(1, 0, 'AdaptCMS', 'http://www.adaptcms.com', 'AdaptCMS', '_new', 0, 1, '{date}', '{date}', '0000-00-00 00:00:00'),
(2, 0, 'AdaptCMS API', 'http://api.adaptcms.com', 'AdaptCMS API', '_new', 0, 1, '{date}', '{date}', '0000-00-00 00:00:00');
-- --------------------------------------------------------
INSERT INTO `{prefix}plugin_poll_values` (`id`, `title`, `poll_id`, `votes`) VALUES
(1, 'NBA', 1, 0),
(2, 'NHL', 1, 0),
(3, 'Soccer', 1, 0),
(4, 'NFL', 1, 0),
(5, 'MLB', 1, 0);
-- --------------------------------------------------------
INSERT INTO `{prefix}plugin_polls` (`id`, `article_id`, `title`, `poll_type`, `user_id`, `start_date`, `end_date`, `created`, `modified`, `deleted_time`) VALUES
(1, NULL, 'What is your favorite sport?', NULL, 1, NULL, NULL, '{date}', '{date}', '0000-00-00 00:00:00');
-- --------------------------------------------------------
INSERT INTO `{prefix}roles` (`id`, `title`, `defaults`, `created`, `modified`, `deleted_time`) VALUES
(1, 'admin', 'default-admin', '0000-00-00 00:00:00', '{date}', '0000-00-00 00:00:00'),
(2, 'member', 'default-member', '{date}', '{date}', '0000-00-00 00:00:00'),
(3, 'guest', 'default-guest', '{date}', '{date}', '0000-00-00 00:00:00'),
(4, 'staff', NULL, '{date}', '{date}', '0000-00-00 00:00:00');
-- --------------------------------------------------------
INSERT INTO `{prefix}settings` (`id`, `title`, `created`, `deleted_time`) VALUES
(1, 'Site Info', '{date}', '0000-00-00 00:00:00'),
(2, 'Appearance', '{date}', '0000-00-00 00:00:00'),
(3, 'Users', '{date}', '0000-00-00 00:00:00'),
(4, 'Articles', '{date}', '0000-00-00 00:00:00'),
(5, 'Admin', '{date}', '0000-00-00 00:00:00'),
(6, 'Comments', '{date}', '0000-00-00 00:00:00');
-- --------------------------------------------------------
INSERT INTO `{prefix}setting_values` (`id`, `title`, `description`, `data`, `data_options`, `setting_type`, `setting_id`, `model`, `created`, `modified`, `deleted_time`) VALUES
(1, 'Site Name', '<p>Fill in the name of your website.</p>', 'AdaptCMS Install', NULL, 'text', 1, NULL, '{date}', '{date}', '0000-00-00 00:00:00'),
(2, 'Webmaster Email', '<p>Provider the email of the webmaster/site owner.</p>', 'no-reply@example.com', NULL, 'text', 1, NULL, '{date}', '{date}', '0000-00-00 00:00:00'),
(5, 'default-theme', '', 'Default', NULL, 'text', 2, NULL, '{date}', '{date}', '0000-00-00 00:00:00'),
(8, 'Security Question Options', '<p>Security Questions incase of lost password.</p>', '', '["What was your mothers maiden name?","Name of your first pet?","Color of your first car?","Your favorite sport?"]', 'dropdown', 3, NULL, '{date}', '{date}', '0000-00-00 00:00:00'),
(9, 'Security Questions', '<p>How many must a user select when signing up?</p>', '2', '["0","1","2","3"]', 'dropdown', 3, NULL, '{date}', '{date}', '0000-00-00 00:00:00'),
(10, 'Number of Articles on Homepage', '', '5', NULL, 'text', 4, NULL, '{date}', '{date}', '0000-00-00 00:00:00'),
(11, 'Categories of Articles to show on homepage', '<p>Separate by a comma, the categories of articles to display on the homepage. Leave blank to allow all.</p>', '', NULL, 'text', 4, NULL, '{date}', '{date}', '0000-00-00 00:00:00'),
(12, 'User Status', '<p>Choosing email activation, user must activate their account via an email link sent to them. Staff activation requires one with access to manually activate a user account.</p>', 'Staff Activation', '["Email Activation","Staff Activation"]', 'dropdown', 3, NULL, '{date}', '{date}', '0000-00-00 00:00:00'),
(21, 'User Register Email Subject', '', 'New Account Created', NULL, 'text', 3, NULL, '{date}', '{date}', '0000-00-00 00:00:00'),
(22, 'Number of Articles to list on Category Page', '', '10', NULL, 'text', 4, NULL, '{date}', '{date}', '0000-00-00 00:00:00'),
(23, 'Number of Items Per Page', '', '10', NULL, 'text', 10, NULL, '{date}', '{date}', '0000-00-00 00:00:00'),
(28, 'Comment Post WYSIWYG Editor', '<p>Will the wysiwyg editor be enabled when posting a comment?</p>', 'Yes', '["Yes","No"]', 'dropdown', 6, NULL, '{date}', '{date}', '0000-00-00 00:00:00'),
(27, 'Comment Post Flood Limit', '<p>x amount of seconds before a user can post another comment. 30 by default.</p>', '30', NULL, 'text', 6, NULL, '{date}', '{date}', '0000-00-00 00:00:00'),
(26, 'Comment Post Captcha Non-Logged In', '<p>Does a non-logged in user have to enter in a captcha code, to have their comment posted?</p>\r\n<p>*note* The guest group must have permission to view an article/to post a comment, in order for this to have effect.</p>', 'Yes', '["Yes","No"]', 'dropdown', 6, NULL, '{date}', '{date}', '0000-00-00 00:00:00'),
(25, 'Registration Captcha', '<p>When signing up, will a re-captcha be shown? (and is required - we recommend to keep this enabled)</p>', 'Yes', '["Yes","No"]', 'radio', 3, NULL, '{date}', '{date}', '0000-00-00 00:00:00'),
(24, 'User Password Reset', '<p>Set this to 0 to disable, if more than 0 then x is the amount of days that can pass before a new password is required. This is mandated upon login.</p>', '0', NULL, 'text', 3, NULL, '{date}', '{date}', '0000-00-00 00:00:00'),
(29, 'Is Registration Open?', '<p>If set to "No", then users cannot register.</p>', 'Yes', '["Yes","No"]', 'dropdown', 3, NULL, '{date}', '{date}', '0000-00-00 00:00:00'),
(30, 'Closed Registration Message', '', '<p>You cannot register at the moment.</p>', NULL, 'textarea', 3, NULL, '{date}', '{date}', '0000-00-00 00:00:00'),
(31, 'Comment Allowed HTML', '<p>Allowed HTML tags when posting a comment. Entering in nothing will result in all HTML being stripped.</p>', '<strong>,<a>,<p>,<br>', NULL, 'text', 6, NULL, '{date}', '{date}', '0000-00-00 00:00:00'),
(32, 'RSS Description', '<p>Enter in a description that will appear in your RSS feed.</p>', 'This is your website''s RSS feed, enter in a little bit about your website.', NULL, 'textarea', 4, NULL, '{date}', '{date}', '0000-00-00 00:00:00');
-- --------------------------------------------------------
INSERT INTO `{prefix}themes` (`id`, `title`, `created`, `modified`, `deleted_time`) VALUES
(1, 'Default', '{date}', '{date}', '0000-00-00 00:00:00');
